#!/usr/bin/env bash

# These must also be updated in build.xml
version=0.5.1
meteor_version=1.5
beer_version=1.0

scriptDir=$(dirname $0)
libDir=$scriptDir/lib
meteorPath=$libDir/meteor-$meteor_version
meteorUrl=http://www.cs.cmu.edu/~alavie/METEOR/download/meteor-${meteor_version}.tar.gz

#meteorJar=$meteorPath/meteor-${meteor_version}.jar
beerJar=${scriptDir}/../../beer_${beer_version}.jar
meteorJar=${scriptDir}/../meteor-${meteor_version}/meteor-${meteor_version}.jar
terJar=$scriptDir/lib/tercom-0.8.0.jar
